apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nextflow-run-config
    files:
      - nextflow.config
      - params.yaml
      - entrypoint.sh
      - reference.sh
    options:
      immutable: true
